import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/common/NavHeader/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'OpenTable',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="bg-gray-100 min-h-screen w-screen text-black">
        <main className="m-auto bg-white">
            <Navbar/>
            {children}
        </main>
      </main>
        </body>
    </html>
  )
}
